# Dependencies
markdown:         redcarpet
highlighter:      pygments

# Setup
title:            mrjimath
tagline:          'Neighborhood, 3.14-friendly math teacher.'
description:      'Neighborhood, 3.14-friendly math teacher.'
url:              http://mrjimath.github.io
baseurl:          /

author:
  name:           'Kevin Ji'
  url:            https://twitter.com/mrjimath

paginate:         5

# Custom vars
version:          

github:
  repo:           
